ALTER TABLE corsi
  DROP COLUMN lun,
  DROP COLUMN mar,
  DROP COLUMN merc,
  DROP COLUMN giov,
  DROP COLUMN ven,
  DROP COLUMN sab,
  DROP COLUMN dom,
  ADD COLUMN lun_inizio TIME NULL AFTER orari,
  ADD COLUMN lun_fine TIME NULL AFTER lun_inizio,
  ADD COLUMN mar_inizio TIME NULL AFTER lun_fine,
  ADD COLUMN mar_fine TIME NULL AFTER mar_inizio,
  ADD COLUMN mer_inizio TIME NULL AFTER mar_fine,
  ADD COLUMN mer_fine TIME NULL AFTER mer_inizio,
  ADD COLUMN gio_inizio TIME NULL AFTER mer_fine,
  ADD COLUMN gio_fine TIME NULL AFTER gio_inizio,
  ADD COLUMN ven_inizio TIME NULL AFTER gio_fine,
  ADD COLUMN ven_fine TIME NULL AFTER ven_inizio,
  ADD COLUMN sab_inizio TIME NULL AFTER ven_fine,
  ADD COLUMN sab_fine TIME NULL AFTER sab_inizio,
  ADD COLUMN dom_inizio TIME NULL AFTER sab_fine,
  ADD COLUMN dom_fine TIME NULL AFTER dom_inizio;
